parent=base
import=common/keycloak

styles=css/styles.css
scripts=js/script.js
locales=en,fr,es
appVersion=V.01.34
meta=viewport==width=device-width,initial-scale=1

kcHtmlClass=mytheme-page
kcBodyClass=mytheme-body
kcLoginClass=mytheme-login
kcHeaderClass=mytheme-header
kcHeaderWrapperClass=mytheme-brand
kcFormCardClass=mytheme-form-panel
kcFormHeaderClass=mytheme-form-panel
kcFormGroupClass=mytheme-form-group
kcFormGroupErrorClass=mytheme-form-group-error
kcLabelClass=mytheme-label
kcLabelWrapperClass=mytheme-label-wrapper
kcInputClass=mytheme-input
kcInputWrapperClass=mytheme-input-wrapper
kcInputGroup=mytheme-input-group
kcInputErrorMessageClass=mytheme-input-error
kcFormOptionsClass=mytheme-form-options
kcFormOptionsWrapperClass=mytheme-form-options-wrapper
kcFormButtonsClass=mytheme-form-buttons
kcFormSettingClass=mytheme-form-settings
kcFormSocialAccountSectionClass=mytheme-social
kcFormSocialAccountListClass=mytheme-social-list
kcFormSocialAccountListGridClass=mytheme-social-grid
kcFormSocialAccountListButtonClass=mytheme-social-btn
kcFormSocialAccountListButtonDisabledClass=mytheme-social-btn-disabled
kcFormSocialAccountNameClass=mytheme-social-name
kcFormSocialAccountGridItem=mytheme-social-grid-item
kcSignUpClass=mytheme-signup
kcInfoAreaWrapperClass=mytheme-info
kcAlertClass=mytheme-alert
kcAlertTitleClass=mytheme-alert-title
kcFeedbackErrorIcon=mytheme-alert-icon mytheme-alert-icon-error
kcFeedbackWarningIcon=mytheme-alert-icon mytheme-alert-icon-warning
kcFeedbackSuccessIcon=mytheme-alert-icon mytheme-alert-icon-success
kcFeedbackInfoIcon=mytheme-alert-icon mytheme-alert-icon-info
kcResetFlowIcon=mytheme-icon-reset

## Locale
kcLocaleMainClass=mytheme-locale
kcLocaleWrapperClass=mytheme-locale-wrapper
kcLocaleDropDownClass=mytheme-locale-dropdown
kcLocaleListClass=mytheme-locale-list
kcLocaleListItemClass=mytheme-locale-list-item
kcLocaleItemClass=mytheme-locale-link

## Buttons
kcButtonClass=mytheme-btn
kcButtonPrimaryClass=mytheme-btn-primary
kcButtonDefaultClass=mytheme-btn-secondary
kcButtonLargeClass=mytheme-btn-lg
kcButtonBlockClass=mytheme-btn-block

## Input
kcInputLargeClass=mytheme-input-lg

## Password visibility
kcFormPasswordVisibilityButtonClass=mytheme-toggle
kcFormPasswordVisibilityIconShow=mytheme-eye
kcFormPasswordVisibilityIconHide=mytheme-eye-slash

## Select authenticator
kcSelectAuthListClass=mytheme-select-auth-list
kcSelectAuthListItemClass=mytheme-select-auth-item
kcSelectAuthListItemIconClass=mytheme-select-auth-icon
kcSelectAuthListItemIconPropertyClass=mytheme-select-auth-icon-property
kcSelectAuthListItemBodyClass=mytheme-select-auth-body
kcSelectAuthListItemHeadingClass=mytheme-select-auth-heading
kcSelectAuthListItemDescriptionClass=mytheme-select-auth-desc
kcSelectAuthListItemFillClass=mytheme-select-auth-fill
kcSelectAuthListItemArrowClass=mytheme-select-auth-arrow
kcSelectAuthListItemArrowIconClass=mytheme-select-auth-arrow-icon
kcSelectAuthListItemTitle=mytheme-select-auth-title
